apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-quarkus-crud-demo
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/raphaelmorsch/devspaces-quarkus-crud-demo.git
    path: deploy/k8s
    directory:
      include: '*'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
